CREATE TABLE REGISTER
(
USER_NO NUMBER,
ACCID VARCHAR2(15),
PASSWORD VARCHAR2(20), 
NAME VARCHAR2(15),
AGE NUMBER,
GENDER VARCHAR2(5),
EMAIL VARCHAR2(30),
REGDATE DATE,
PRIMARY KEY(USER_NO)
)

ALTER TABLE REGISTER
ADD
CONSTRAINT GENDER_CK_CHECK CHECK (GENDER IN ('MALE','FEMALE'))

CREATE TABLE ACCOUNTMGR
(
ACCOUNTNO NUMBER,
ACCOUNT VARCHAR2(20),
ACCTYPE VARCHAR2(20),
INTEREST NUMBER,
BALANCE NUMBER,
USER_NO NUMBER,
USAGE VARCHAR2(5),
PRIMARY KEY(ACCOUNTNO)
)

ALTER TABLE ACCOUNTMGR
ADD
CONSTRAINT USRNO_FK FOREIGN KEY(USER_NO) REFERENCES REGISTER(USER_NO)

ALTER TABLE ACCOUNTMGR
ADD
CONSTRAINT USAGE_CK_CHECK CHECK (USAGE IN ('TRUE','FALSE'))

ALTER TABLE ACCOUNTMGR
ADD
CONSTRAINT ACCTYPE_CK_CHECK CHECK (ACCTYPE IN ('CREDIT','CASH','ACC', 'STOCK', 'DEBIT'))

CREATE TABLE INCOME
(
INC_SQ NUMBER,
USER_NO NUMBER,
AMOUNTS NUMBER,
MEMO VARCHAR2(50),
INC_DATE DATE,
ACCOUNTNO NUMBER,
CATEGORYNO NUMBER,
PRIMARY KEY(USER_NO)
)

ALTER TABLE INCOME
ADD
CONSTRAINT USRNO_INC_FK FOREIGN KEY(USER_NO) REFERENCES REGISTER(USER_NO)

ALTER TABLE INCOME
ADD
CONSTRAINT ACTNO_FK FOREIGN KEY(ACCOUNTNO) REFERENCES ACCOUNTMGR(ACCOUNTNO)

ALTER TABLE INCOME
ADD
CONSTRAINT CATNO_INC_FK FOREIGN KEY(CATEGORYNO) REFERENCES CATEGORYMGR(CATEGORYNO)


CREATE TABLE EXPENSES
(
EXP_SQ NUMBER,
USER_NO NUMBER,
AMOUNTS NUMBER,
MEMO VARCHAR2(50),
EXP_DATE DATE,
ACCOUNTNO NUMBER,
CATEGORYNO NUMBER,
PRIMARY KEY(EXP_SQ)
)
drop table INCOME

ALTER TABLE EXPENSES
ADD
CONSTRAINT USRNO_EXP_FK FOREIGN KEY(USER_NO) REFERENCES REGISTER(USER_NO)

ALTER TABLE EXPENSES
ADD
CONSTRAINT ACTNO_EXP_FK FOREIGN KEY(ACCOUNTNO) REFERENCES ACCOUNTMGR(ACCOUNTNO)

ALTER TABLE EXPENSES
ADD
CONSTRAINT CATNO_EXP_FK FOREIGN KEY(CATEGORYNO) REFERENCES CATEGORYMGR(CATEGORYNO)


CREATE TABLE CATEGORYMGR
(
CATEGORYNO NUMBER,
CATEGORY VARCHAR2(20),
CATTYPE VARCHAR2(20),
BUDGET NUMBER,
BALANCE NUMBER,
USER_NO NUMBER,
PRIMARY KEY(CATEGORYNO)
)


ALTER TABLE CATEGORYMGR
ADD
CONSTRAINT USRNO_CAT_FK FOREIGN KEY(USER_NO) REFERENCES REGISTER(USER_NO)

ALTER TABLE CATEGORYMGR
ADD
CONSTRAINT USRNO_CAT_UK UNIQUE (USER_NO)



DROP TABLE CATEGORYMGR


SELECT * FROM REGISTER
SELECT * FROM ACCOUNTMGR
SELECT * FROM INCOME
SELECT * FROM EXPENSES
SELECT * FROM CATEGORYMGR

select max(EXP_SQ) from EXPENSES

insert into REGISTER
(USER_NO, ACCID, PASSWORD, NAME, AGE, GENDER, EMAIL, REGDATE)
values (100001, 'ryon81', 1111, '전영민', 35, 'MALE', 'ryon81@nate.com', sysdate)

insert into CATEGORYMGR
(CATEGORYNO, CATEGORY, CATTYPE, BUDGET, BALANCE, USER_NO)
values (800001, '생활비', '생활비', 300, 300, 100001)

insert into ACCOUNTMGR
(ACCOUNTNO, ACCOUNT, ACCTYPE, INTEREST, BALANCE, USER_NO, USAGE)
values (12345678912, '국민은행', 'ACC', 5, 999, 100001, 'TRUE')

insert into EXPENSES
(EXP_SQ, USER_NO, AMOUNTS, MEMO, EXP_DATE, ACCOUNTNO, CATEGORYNO)
values (300001, 100001, 500, '생활비', sysdate, 12345678912, 800001)



